import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface ArticleData {
  title: string;
  content: string;
  author?: {
    nickname?: string;
    username?: string;
  };
  publishedAt?: string;
  createTime?: string;
  category?: {
    name?: string;
  };
  coverImage?: string;
}

/**
 * 将文章内容导出为PDF
 * @param article 文章数据
 * @param contentElement 文章内容DOM元素
 */
export const exportArticleToPDF = async (
  article: ArticleData,
  contentElement?: HTMLElement
): Promise<void> => {
  try {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    
    let currentY = margin;
    
    // 添加标题
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(article.title, contentWidth);
    doc.text(titleLines, margin, currentY);
    currentY += titleLines.length * 8 + 5;
    
    // 添加作者信息
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const authorName = article.author?.nickname || article.author?.username || '匿名作者';
    const publishDate = article.publishedAt || article.createTime || new Date().toLocaleDateString('zh-CN');
    const categoryName = article.category?.name || '未分类';
    
    doc.setTextColor(100, 100, 100);
    doc.text(`作者: ${authorName}  |  分类: ${categoryName}  |  发布时间: ${publishDate}`, margin, currentY);
    currentY += 10;
    
    // 添加分隔线
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, currentY, pageWidth - margin, currentY);
    currentY += 10;
    
    // 如果有内容元素，使用html2canvas渲染
    if (contentElement) {
      // 创建临时容器，只包含纯文本内容
      const tempDiv = document.createElement('div');
      tempDiv.innerHTML = article.content;
      tempDiv.style.width = '800px';
      tempDiv.style.padding = '20px';
      tempDiv.style.backgroundColor = 'white';
      tempDiv.style.color = 'black';
      tempDiv.style.fontSize = '14px';
      tempDiv.style.lineHeight = '1.8';
      tempDiv.style.position = 'absolute';
      tempDiv.style.left = '-9999px';
      document.body.appendChild(tempDiv);
      
      try {
        const canvas = await html2canvas(tempDiv, {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: '#ffffff'
        });
        
        const imgData = canvas.toDataURL('image/png');
        const imgWidth = contentWidth;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        
        // 如果内容超过一页，需要分页
        let heightLeft = imgHeight;
        let position = currentY;
        
        // 添加第一页
        doc.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);
        heightLeft -= (pageHeight - currentY - margin);
        
        // 添加后续页
        while (heightLeft > 0) {
          doc.addPage();
          position = -pageHeight + margin + heightLeft + imgHeight;
          doc.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);
          heightLeft -= (pageHeight - margin * 2);
        }
      } finally {
        document.body.removeChild(tempDiv);
      }
    } else {
      // 纯文本模式
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      
      // 移除HTML标签
      const plainText = article.content
        .replace(/<[^>]+>/g, '\n')
        .replace(/&nbsp;/g, ' ')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&')
        .replace(/\n\s*\n/g, '\n')
        .trim();
      
      const textLines = doc.splitTextToSize(plainText, contentWidth);
      
      // 分页处理
      let remainingLines = textLines;
      while (remainingLines.length > 0) {
        const availableHeight = pageHeight - currentY - margin;
        const linesPerPage = Math.floor(availableHeight / 6);
        
        const pageLines = remainingLines.slice(0, linesPerPage);
        doc.text(pageLines, margin, currentY);
        
        remainingLines = remainingLines.slice(linesPerPage);
        
        if (remainingLines.length > 0) {
          doc.addPage();
          currentY = margin;
        }
      }
    }
    
    // 添加页脚
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`第 ${i} 页 / 共 ${totalPages} 页`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      doc.text('Generated by MyVlog', pageWidth - margin, pageHeight - 10, { align: 'right' });
    }
    
    // 保存PDF
    const fileName = `${article.title.replace(/[^\w\u4e00-\u9fa5]/g, '_')}.pdf`;
    doc.save(fileName);
    
  } catch (error) {
    console.error('PDF导出失败:', error);
    throw new Error('PDF导出失败，请重试');
  }
};

/**
 * 简单的PDF导出（纯文本）
 * @param article 文章数据
 */
export const exportArticleToPDFSimple = (article: ArticleData): void => {
  try {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    
    let currentY = margin;
    
    // 标题
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(article.title, contentWidth);
    doc.text(titleLines, margin, currentY);
    currentY += titleLines.length * 8 + 5;
    
    // 作者信息
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    const authorName = article.author?.nickname || article.author?.username || '匿名作者';
    const publishDate = article.publishedAt || article.createTime || new Date().toLocaleDateString('zh-CN');
    doc.text(`作者: ${authorName}  |  发布时间: ${publishDate}`, margin, currentY);
    currentY += 10;
    
    // 分隔线
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, currentY, pageWidth - margin, currentY);
    currentY += 10;
    
    // 内容
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    
    // 清理HTML标签
    const plainText = article.content
      .replace(/<[^>]+>/g, '\n')
      .replace(/&nbsp;/g, ' ')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&amp;/g, '&')
      .replace(/\n\s*\n/g, '\n')
      .trim();
    
    const textLines = doc.splitTextToSize(plainText, contentWidth);
    
    // 分页
    let remainingLines = textLines;
    while (remainingLines.length > 0) {
      const availableHeight = 297 - currentY - margin;
      const linesPerPage = Math.floor(availableHeight / 5.5);
      
      const pageLines = remainingLines.slice(0, linesPerPage);
      doc.text(pageLines, margin, currentY);
      
      remainingLines = remainingLines.slice(linesPerPage);
      
      if (remainingLines.length > 0) {
        doc.addPage();
        currentY = margin;
      }
    }
    
    // 页脚
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`第 ${i} 页 / 共 ${totalPages} 页`, pageWidth / 2, 287, { align: 'center' });
    }
    
    const fileName = `${article.title.replace(/[^\w\u4e00-\u9fa5]/g, '_')}.pdf`;
    doc.save(fileName);
    
  } catch (error) {
    console.error('PDF导出失败:', error);
    throw new Error('PDF导出失败，请重试');
  }
};
